"""Wrappers around systemd/util-linux tools used by `hc mount`.

Shells out to the real tools (systemd-escape, systemctl, findmnt, df,
journalctl) rather than reimplementing any of their logic — getting unit
name escaping or active-state checks subtly wrong causes mounts to silently
fail to bind or status to lie about what's actually live. Linux-only by
nature: there's no meaningful stand-in for any of this on other platforms.
"""
from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .registry import MountSpec

UNIT_DIR = Path("/etc/systemd/system")
DOCKER_DROPIN_DIR = UNIT_DIR / "docker.service.d"
DOCKER_DROPIN_PATH = DOCKER_DROPIN_DIR / "wait-for-mounts.conf"
MANAGED_HEADER = "# Managed by hc — do not edit directly."


class SystemdError(SystemExit):
    pass


def _run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    try:
        return subprocess.run(cmd, **kwargs)
    except FileNotFoundError as exc:
        raise SystemdError(f"{cmd[0]} not found on PATH: {exc}")


def escape_unit_name(target: str) -> str:
    """Systemd unit filename for a mount point, e.g. /srv/jellyfin/media -> srv-jellyfin-media.mount.

    Deriving this from `target` (not the spec's friendly `name`) is load-bearing:
    systemd requires the unit filename to match the escaped mount path, or the
    unit silently fails to bind to the mount point.
    """
    result = _run(
        ["systemd-escape", "--path", "--suffix=mount", target],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemdError(f"systemd-escape failed for '{target}': {result.stderr.strip()}")
    return result.stdout.strip()


def render_unit(spec: MountSpec, unit_names: dict[str, str], source_ref: str) -> str:
    """Render a mount spec into unit file text.

    unit_names maps every registered spec's friendly `name` (plus every
    declared pool's name) to its resolved systemd unit filename, so
    depends_on can be turned into the right After=/Requires= target
    regardless of processing order.
    """
    lines = [f"{MANAGED_HEADER} Source: {source_ref}", "[Unit]"]
    if spec.description:
        lines.append(f"Description={spec.description}")
    if spec.depends_on:
        dep_unit = unit_names[spec.depends_on]
        lines.append(f"After={dep_unit}")
        lines.append(f"Requires={dep_unit}")

    options = ",".join(spec.options) if spec.options else spec.type
    lines += [
        "",
        "[Mount]",
        f"What={spec.source}",
        f"Where={spec.target}",
        f"Type={spec.type}",
        f"Options={options}",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
        "",
    ]
    return "\n".join(lines)


def render_docker_dropin(unit_names: list[str]) -> str:
    deps = " ".join(unit_names)
    return (
        f"{MANAGED_HEADER} Regenerated by `hc mount sync`.\n"
        "[Unit]\n"
        f"After={deps}\n"
        f"Requires={deps}\n"
    )


@dataclass
class UnitDiff:
    added: list[str]
    changed: list[str]
    removed: list[str]


def discover_managed_units() -> dict[str, str]:
    """unit filename -> current content, for every hc-managed *.mount unit on disk.

    Only files carrying MANAGED_HEADER are considered hc's to remove — an
    unrelated .mount unit on the host is never touched by sync.
    """
    if not UNIT_DIR.exists():
        return {}
    managed = {}
    for path in UNIT_DIR.glob("*.mount"):
        text = path.read_text()
        if text.startswith(MANAGED_HEADER):
            managed[path.name] = text
    return managed


def sync_units(rendered: dict[str, str], *, force: bool = False) -> UnitDiff:
    """Write rendered unit files to disk; report added/changed/removed vs. current hc-managed units.

    `rendered` is unit filename -> full unit file content, for every mount
    currently registered for this host. Any hc-managed unit file NOT in this
    set is a removal candidate, since sync always regenerates from the full
    registry state. A removal candidate that's currently active is left in
    place (raising, unless force=True) so a registry change can't silently
    tear down a live mount.
    """
    existing = discover_managed_units()
    added, changed, removed = [], [], []

    for unit_name, content in rendered.items():
        if unit_name not in existing:
            added.append(unit_name)
        elif existing[unit_name] != content:
            changed.append(unit_name)
        (UNIT_DIR / unit_name).write_text(content)

    for unit_name in existing:
        if unit_name in rendered:
            continue
        if is_active(unit_name):
            if not force:
                raise SystemdError(
                    f"refusing to remove {unit_name}: it's currently active — "
                    # unit_name is the systemd-escaped unit filename, not the registry's
                    # friendly spec name, and the spec is often already gone from the
                    # registry by the time this fires — `systemctl` is the one command
                    # guaranteed to still resolve it.
                    f"run `systemctl disable --now {unit_name}` first, or pass --force"
                )
            # Deleting the unit file alone wouldn't stop it — systemd tracks a live
            # mount from /proc/self/mountinfo independent of whether a unit file
            # defines it, so it would keep running, invisible to hc, until something
            # stops it by hand. --force means "yes, actually tear it down."
            disable_now(unit_name)
        (UNIT_DIR / unit_name).unlink()
        removed.append(unit_name)

    return UnitDiff(added=added, changed=changed, removed=removed)


def sync_docker_dropin(unit_names: list[str]) -> bool:
    """Regenerate the docker.service drop-in from the full current mount list.

    Returns True if the content actually changed.
    """
    content = render_docker_dropin(unit_names)
    previous = DOCKER_DROPIN_PATH.read_text() if DOCKER_DROPIN_PATH.exists() else None
    if previous == content:
        return False
    DOCKER_DROPIN_DIR.mkdir(parents=True, exist_ok=True)
    DOCKER_DROPIN_PATH.write_text(content)
    return True


def daemon_reload() -> None:
    result = _run(["systemctl", "daemon-reload"], check=False)
    if result.returncode != 0:
        raise SystemdError(f"systemctl daemon-reload failed (exit {result.returncode})")


def enable_now(unit: str) -> None:
    result = _run(["systemctl", "enable", "--now", unit], check=False)
    if result.returncode != 0:
        raise SystemdError(f"failed to enable {unit} (exit {result.returncode})")


def disable_now(unit: str) -> None:
    result = _run(["systemctl", "disable", "--now", unit], check=False)
    if result.returncode != 0:
        raise SystemdError(f"failed to disable {unit} (exit {result.returncode})")


def restart_unit(unit: str) -> None:
    result = _run(["systemctl", "restart", unit], check=False)
    if result.returncode != 0:
        raise SystemdError(f"failed to restart {unit} (exit {result.returncode})")


def is_active(unit: str) -> bool:
    result = _run(["systemctl", "is-active", "--quiet", unit], check=False)
    return result.returncode == 0


def show(unit: str, properties: list[str]) -> dict[str, str]:
    """systemctl show <unit> -p <prop> [-p <prop> ...] --value, zipped back to property names."""
    args = ["systemctl", "show", unit]
    for prop in properties:
        args += ["-p", prop]
    args.append("--value")
    result = _run(args, capture_output=True, text=True, check=False)
    values = result.stdout.splitlines()
    values += [""] * (len(properties) - len(values))
    return dict(zip(properties, values))


def findmnt(target: str) -> dict | None:
    """Ground truth on whether `target` is actually mounted, independent of systemd's view."""
    if not target:
        return None
    result = _run(["findmnt", "--json", target], capture_output=True, text=True, check=False)
    if result.returncode != 0 or not result.stdout.strip():
        return None
    filesystems = json.loads(result.stdout).get("filesystems") or []
    return filesystems[0] if filesystems else None


def disk_usage(target: str) -> tuple[str, str] | None:
    """(avail, use%) for `target`, or None if df can't report on it."""
    result = _run(
        ["df", "-h", "--output=avail,pcent", target],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    lines = result.stdout.strip().splitlines()
    if len(lines) < 2:
        return None
    avail, pcent = lines[1].split()
    return avail, pcent


def journal_tail(unit: str, lines: int = 20) -> str:
    result = _run(
        ["journalctl", "-u", unit, "-n", str(lines), "--no-pager"],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout
